name: reservecom
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.10.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  cached_network_image: ^2.5.0
  modal_bottom_sheet: ^1.0.0
  dio: ^3.0.10
  flutter_dotenv: ^3.0.2
  get_it: ^5.0.6
  provider: ^4.3.3
  flutter_svg: ^0.19.1
  shared_preferences: ^0.5.12+4
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  firebase_analytics: ^7.0.1
  bubble: ^1.2.1
  dash_chat: ^1.1.15
  google_fonts: ^2.0.0
  image_cropper: ^1.3.0
  toast: ^0.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/stevejobs.jpeg
    - assets/images/stevewozniak.jpeg
    - assets/icons/apartment.png
    - assets/icons/building.png
    - assets/icons/home.png
    - assets/icons/park.png
    - assets/icons/parking.png
    - assets/icons/room.png
    - assets/icons/bell.svg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
